### ISSUE TITLE
CLA, commercial use, contributor compensation, etc

### ISSUE THREAD

**Issue by IS2511** [ScuffleTV/scuffle#14]
Since we haven't solved the issue of commercial use by us vs other companies, this issue should exist.

Taking from https://github.com/ScuffleTV/scuffle/issues/9#issuecomment-1408296941
> I assume you want to prohibit big companies from commercial use, but you'll need to make an exception for yourself. Related: https://opensource.stackexchange.com/questions/4875/open-source-license-to-prevent-commercial-use
> Basically, it should be possible to achieve what you want, but with much effort. The general strategy seems to be [open-source license like GNU GPLv3] for non-commercial use, contributor agreement to maintain ownership of the whole project, separate commercial license.
> It's also of note that prohibiting commercial use might be against point 6 of the OSD https://opensource.org/osd-annotated

The open-source license is picked, so that part is done. But we have no CLA, no commercial use prohibition and no commercial use license.
And without an agreement on how contributors will get shares or any other form of compensation, it all relies on a word of honor from @TroyKomodo (company owner), which might be not enough for a lot of contributors.

**Comment by TroyKomodo** [comment]
I agree, I will work on getting a CLA, and looking into a commercial license agreement.

> agreement on how contributors will get shares

This is a bit of a iffy situation. 
Currently in the early stage in which we are at the company we are not really able to do that. 
If your soul purpose for contributing on this project is to get shares then I would advise you to not contribute.  

At the time of writing we are not funded by a VC we do not have hiring capital, we do not generate a revenue.

The idea around giving shares to contributors still stands. However it is not just you write some code and you get some shares. Its when I notice that you are over the course of the project you have decided to take an effort to help with building out this platform and are active and are reliable. To which then I will be the one who reaches out and offers you a share contract. Having a guideline might prove tricky because the question becomes is what do I see as "quantified effort". And having it in a guideline creates this weird environment where people will aim to follow the guideline as a checklist, aiming to acquire shares and then poof as soon as they get them.

I am aiming to cheat people.
This is an opensource project, most opensource projects do not have this prospect of earning share. Most people are likely not even aware of the fact that there is a possibility of earning shares.  

> which might be not enough for a lot of contributors

This is fine, I would rather not want people to contribute if they are concerned about the legal grounds of compensation for their contributions. The whole idea of the project is to make something cool and to have fun while doing it. To be able to play around with a real production environment and have it cost virtually nothing.

Hope that clears it up a bit.

**Comment by IS2511** [comment]
> And having it in a guideline creates this weird environment where people will aim to follow the guideline as a checklist

Yeah, it's basically impossible to formally define guidelines that won't be cheated/circumvented/etc. It's not in our interests for people to be optimizing their work to some abstract guidelines instead of just making good contributions.

Simply put, shares are more of a bonus. We should just think of it like a regular open-source project Okayge 👍
